name: Build pif

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install apktool
        run: sudo apt-get install -y apktool
      
      - name: Grant execute permission for script
        run: chmod +x pif.sh

      - name: Generate JSON file
        run: ./pif.sh

      - name: Check differences in custom.pif.json
        run: |
          if git diff --exit-code custom.pif.json; then
            echo "custom.pif.json is the same, no need to commit."
          else
            git config --global user.name "tzagim"
            git config --global user.email "username@users.noreply.github.com"
            git add custom.pif.json
            git commit -m "Update custom.pif.json"
            git push
          fi
